# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: GitHub Release Actions

on:
  release:
    types: [published]

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
    - name: Run GitHub Release CI workflow
      uses: adafruit/workflows-circuitpython-libs/release-gh@main
      with:
        github-token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
        upload-url: {% raw %}${{ github.event.release.upload_url }}{% endraw %}{% if cookiecutter.target_bundle != 'Adafruit' %}
        # TODO: If you're creating a package (library is a folder), add this
        # argument along with the prefix (or full name) of the package folder
        # so the  MPY bundles are built correctly:s
        # package-prefix: {{ cookiecutter.__libprefix }}{{ cookiecutter.__libname }}
{%- endif %}
